name: Access files

on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "hoge"
